repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        exclude: test/mocks
        types_or: ["c", "c++"]
      - id: earthly-lint
        name: Run earthly ls to lint Earthfile
        entry: /bin/sh -c 'for n in $(seq 0 "$#"); do echo "Checking ${!n}"; earthly ls "./${!n}" >/dev/null; done'
        files: Earthfile$
        language: system
